In [11]:
# Jack Import Monthly Data
import pandas as pd 

monthly_data = "Data/monthy_data1.csv"

monthly_data_df = pd.read_csv(monthly_data, encoding="ISO-8859-1") 

monthly_data_df.head()

,ï»¿Year,Month,FIPS,Beverage,Gallons,Ethanol,Population,PerCapita,State
0,2017,1,2,1,103645,42598,593378,0.0718,Alaska
1,2017,1,5,1,402885,165586,2455022,0.0674,Arkansas
2,2017,1,8,1,733857,301615,4634346,0.0651,Colorado
3,2017,1,9,1,412100,169373,3015481,0.0562,Connecticut
4,2017,1,10,1,180388,74139,799550,0.0927,Delaware

In [12]:
# Check column headers

## For Beverages
# 1 is spirits
# 2 is wine
# 3 is beer

list(monthly_data_df.columns.values)

['ï»¿Year',
 'Month',
 'FIPS',
 'Beverage',
 'Gallons',
 'Ethanol',
 'Population',
 'PerCapita',
 'State']

In [13]:
monthly_data_df = monthly_data_df.rename(columns={"ï»¿Year": "Year"})
monthly_data_df.head()

,Year,Month,FIPS,Beverage,Gallons,Ethanol,Population,PerCapita,State
0,2017,1,2,1,103645,42598,593378,0.0718,Alaska
1,2017,1,5,1,402885,165586,2455022,0.0674,Arkansas
2,2017,1,8,1,733857,301615,4634346,0.0651,Colorado
3,2017,1,9,1,412100,169373,3015481,0.0562,Connecticut
4,2017,1,10,1,180388,74139,799550,0.0927,Delaware

In [16]:
count_by_state_df = monthly_data_df.groupby(['State']).count()
count_by_state_df

,Year,Month,FIPS,Beverage,Gallons,Ethanol,Population,PerCapita
State,,,,,,,,
Alaska,132,132,132,132,132,132,132,132
Arkansas,132,132,132,132,132,132,132,132
Colorado,132,132,132,132,132,132,132,132
Connecticut,129,129,129,129,129,129,129,129
Delaware,129,129,129,129,129,129,129,129
Florida,129,129,129,129,129,129,129,129
Illinois,132,132,132,132,132,132,132,132
Kansas,88,88,88,88,88,88,88,88
Kentucky,132,132,132,132,132,132,132,132
Louisiana,84,84,84,84,84,84,84,84
Massachusetts,132,132,132,132,132,132,132,132
Missouri,132,132,132,132,132,132,132,132
North Dakota,132,132,132,132,132,132,132,132
Oregon,88,88,88,88,88,88,88,88
Tennessee,132,132,132,132,132,132,132,132
Texas,132,132,132,132,132,132,132,132
Utah,84,84,84,84,84,84,84,84
Virginia,126,126,126,126,126,126,126,126
Wisconsin,88,88,88,88,88,88,88,88

In [18]:
state_list = monthly_data_df['State'].tolist()
state_list

['Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Virginia',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Virginia',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Virginia',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Virginia',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Virginia',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Virginia',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Virginia',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Virginia',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Virginia',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Virginia',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Virginia',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Virginia',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Virginia',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Virginia',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Virginia',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Virginia',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Virginia',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Virginia',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Wisconsin',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Massachusetts',
 'Missouri',
 'North Dakota',
 'Oregon',
 'Tennessee',
 'Texas',
 'Virginia',
 'Alaska',
 'Arkansas',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Missouri',
 ...]

In [23]:

# Spirits DF

spirits_df = monthly_data_df.loc[monthly_data_df["Beverage"] == 1, :]
spirits_df

,Year,Month,FIPS,Beverage,Gallons,Ethanol,Population,PerCapita,State
0,2017,1,2,1,103645,42598,593378,0.0718,Alaska
1,2017,1,5,1,402885,165586,2455022,0.0674,Arkansas
2,2017,1,8,1,733857,301615,4634346,0.0651,Colorado
3,2017,1,9,1,412100,169373,3015481,0.0562,Connecticut
4,2017,1,10,1,180388,74139,799550,0.0927,Delaware
...,...,...,...,...,...,...,...,...,...
2236,2020,8,29,1,1314526,540270,5077875,0.1064,Missouri
2237,2020,8,38,1,193446,79506,617880,0.1287,North Dakota
2238,2020,8,47,1,1178002,484159,5661532,0.0855,Tennessee
2239,2020,8,48,1,3280388,1348239,23257363,0.0580,Texas
2240,2020,8,55,1,1459821,599987,4851640,0.1237,Wisconsin